stages:
  - staging

staging:
  stage: staging
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=${REPO_NAME} --api-key=${HEROKU_API}
  only:
    - master
  tags:
    - docker